var express = require('express');
var router = express.Router();
var ctrlMain = require("../controllers/cntrlMain");
var modelMain = require("../models/modelMain");

router.get('/', ctrlMain.get_register);
router.get('/admin', ctrlMain.check_admin,ctrlMain.get_admin);
router.post('/register', ctrlMain.post_register);
router.post('/login', ctrlMain.post_login);
router.get('/logout', ctrlMain.check_logged_In, ctrlMain.get_logout);
router.get('/home', ctrlMain.check_logged_In, ctrlMain.get_homePage);
router.get('/overviewCS', ctrlMain.check_logged_In, ctrlMain.get_overview_cs);
router.get('/overviewBusiness', ctrlMain.check_logged_In, ctrlMain.get_overview_business);
router.get('/overviewMedicine', ctrlMain.check_logged_In, ctrlMain.get_overview_medicine);
router.post('/searchResult', ctrlMain.check_logged_In, ctrlMain.post_collegeInfo);
router.post('/add', ctrlMain.post_add);
router.post('/delete', ctrlMain.post_delete);
router.post('/update', ctrlMain.post_update);
router.post('/display', ctrlMain.post_display);
router.post('/populate', ctrlMain.post_populate);
router.get('/showAll', modelMain.showAllUniv);
router.get('/dashboard', ctrlMain.check_logged_In, ctrlMain.get_dashboard);
router.get('/aveExpense', ctrlMain.check_logged_In, modelMain.getSummarizeData);
router.get('/universityInfo', ctrlMain.check_logged_In, modelMain.get_universityInfo);
router.get('/allUniversityInfo', modelMain.get_allUniversityInfo);
router.post('/moreUniversityInfo', ctrlMain.check_logged_In, modelMain.post_detailedUniversityData);
router.get('/contact', ctrlMain.check_logged_In, ctrlMain.get_contact);
router.get('/news', ctrlMain.check_logged_In, ctrlMain.get_news);

module.exports = router;
